### ISSUE TITLE
 [GraphqlDemo-9] Create a docker-compose.yml file for the application

### ISSUE THREAD

**Issue by michal-wybraniec** [dzbvn/Django-GraphQL#15]
This time we need to create a flexible development environment. So let's assume that the application will work with PostgreSQL. Therefore we need to define it in the `docker-compose.yml` file.
The example file would look like this:
```
version: "3"

x-app-defaults: &app_defaults
  build:
    context: .
  env_file: .env
  networks:
    - demo
  volumes:
    - ./GraphQLProject:/home/GraphQLApp/GraphQLProject
  depends_on:
    - db
  working_dir: /home/GraphQLApp

networks:
  demo:
    driver: bridge

services:
  db:
    image: postgres:14
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - demo
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}

  web:
    <<: *app_defaults
    ports:
      - "8000:8000"

```
